Log api/add json key filter
Coreoz/Plume-admin pull request #14
Opened 2023-06-30 14:55 UTC by jfardilha2

2023-07-03 11:26 UTC, lucas-amiaud requested changes

2023-07-03 11:26 UTC, lucas-amiaud commented on plume-admin-api-log/README.md
> +        ["contractId", "password"],
ca ne fonctionne pas ça en Java

2023-07-03 11:26 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +        } else {
pas besoin de else vu que ton "if" fait un return

2023-07-03 11:26 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    default LogEntryTransformer hideJsonFields(List<String> jsonFieldKeysToHide, String replacement) {
si tu regardes la logique des autres c'est pas comme ca qu'il devrait être implémenté ;
- limitBodySizeTransformer par exemple, est static
- il s'appelle en faisant .andApply(LogEntryTransformer.limitBodySizeTransformer(100))
Tu dois donc appliquer la même logique d'implémentation pour celui là

2023-07-03 11:26 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    private LogEntryTransformer jsonFieldTransformer(String regex, String replacement) {
je vois pas trop l'intérêt d'isoler ca dans une méthode à part ; c'est tout le traitement donc tu as besoin pour hideJsonFields, et il ne sera pas réutilisé

2023-07-03 11:26 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    private String regexHidingFields(List<String> keysToHide) {
tu pourrais isoler ca ca dans une autre class, type Regex builder, en méthode statique. Ce traitement n'a pas vraiment sa place dans l'intreface fonctionnelle

2023-07-03 11:26 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +        return (request, response, okhttpApiCallTrace) -> otherTransformerToApplyAfter
je trouve pas le nom okhttpApiCallTrace forcément plus adéquate que apiTrace :
- au final il n'est pas plus compréhensible qu'avant 
- cela doit représenter l'objet qui va être écrit en base après le traitement
donc peut être : apiLogEntry ? je sais pas, à discuter

2023-07-03 11:38 UTC, jfardilha2 commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    private String regexHidingFields(List<String> keysToHide) {
Tu veux que je la mette dans un autre package genre utils ou je le laisse à la racine à côté du LogEntryTransformer ?

2023-07-03 11:38 UTC, jfardilha2 commented on plume-admin-api-log/README.md
> +        ["contractId", "password"],
certes

2023-07-03 11:39 UTC, jfardilha2 commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    default LogEntryTransformer hideJsonFields(List<String> jsonFieldKeysToHide, String replacement) {
Je comprends pas ce que tu veux dire. Pour moi il s'utilise comme le .andApply et pas comme une initialisation

2023-07-03 11:44 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    default LogEntryTransformer hideJsonFields(List<String> jsonFieldKeysToHide, String replacement) {
parce que c'est une application du LogEntryTransformer, un helper si tu veux. Les méthodes d'interface sont plus là pour ajouter des RG au fonctionnement général du LogEntryTransformer (andApply, applyOnlyToRequests, applyOnlyToResponses, ...). C'est comme si tu ajoutais .filterRegex() dans l'interface du Predicate, ca ne fait pas de sens

2023-07-03 11:49 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    private String regexHidingFields(List<String> keysToHide) {
mmh, j'aurais laissé ca à côté de ses copains, même si le package root commence à être chargé. Mais en gros il a le même fonctionnement métier que OkHttpMatchers

2023-07-05 07:30 UTC, lucas-amiaud requested changes

2023-07-05 07:30 UTC, lucas-amiaud commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/RegexBuilder.java
> +public class RegexBuilder {
constructeur privé pour pas que ton builder soit instanciable

2023-07-05 07:30 UTC, lucas-amiaud commented on plume-admin-api-log/src/test/java/com/coreoz/plume/admin/OkHttpLogEntryTransformerTest.java
> +        );
elle s'est perdue cette parenthèse

2023-07-05 07:30 UTC, lucas-amiaud commented on plume-admin-api-log/src/test/java/com/coreoz/plume/admin/OkHttpLogEntryTransformerTest.java
> +        return "{\"id\":\"123456\",\"password\":\"TEST\",\"detail\":\"Détail\"}";
tu peux le mettre en variable statique de classe en haut du fichier

2023-07-05 07:54 UTC, merged