Log api / main
Coreoz/Plume-admin pull request #17
Opened 2023-07-05 07:55 UTC by lucas-amiaud

2023-07-05 07:56 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    static LogEntryTransformer nullifyBody() {
A renommer en `emptyBody`

2023-07-05 07:58 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    static LogEntryTransformer hideJsonFields(List<String> jsonFieldKeysToHide, String replacement) {
Il faudrait ajouter une description (en anglais)

2023-07-05 08:01 UTC, amanteaux commented on plume-admin-api-log/README.md
> +          String newName = logInterceptApiBean.getApiName() + "-HTTPS-1024chars";
Il sert à quoi ce transformer?

2023-07-05 08:02 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/RequestPredicate.java
> +    default RequestPredicate filterUrlRegex(List<String> urlRegexList) {
Il faudrait commenter la fonction

2023-07-05 08:03 UTC, lucas-amiaud commented on plume-admin-api-log/README.md
> +          String newName = logInterceptApiBean.getApiName() + "-HTTPS-1024chars";
limitBodySizeTransformer ? ou le fait de renommer le nom de l'API ?

2023-07-06 09:02 UTC, amanteaux commented on plume-admin-api-log/README.md
> +          String newName = logInterceptApiBean.getApiName() + "-HTTPS-1024chars";
Le fait de renommer le nom de l'API, je ne comprends pas l'exemple

2023-07-06 09:10 UTC, lucas-amiaud commented on plume-admin-api-log/README.md
> +          String newName = logInterceptApiBean.getApiName() + "-HTTPS-1024chars";
c'est juste un exemple ou je modifie 2 choses, mais je peux le faire sauter en vrai

2023-07-06 09:19 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> + * <p>The static method {@link #emptyTransformer()} initiates the transformer
Peut être que tu pourrais le formuler autrement : 

> There are multiple ways to create a transformer:
- Starting from the empty transfomer: {@code LogEntryTransformer.emptyTransformer()}
- Starting using an existing transformer: {@code LogEntryTransformer.limitBodySizeTransformer(1000)} or {@code LogEntryTransformer.hideJsonFields(...)} or {@code LogEntryTransformer.emptyBody()}

2023-07-06 09:23 UTC, amanteaux commented on plume-admin-api-log/README.md
> +          String newName = logInterceptApiBean.getApiName() + "-HTTPS-1024chars";
Je le ferai bien sauter pour plus de clarté : ce cas d'utilisation n'existe pas, et il est un peu confusant je trouve

2023-07-06 09:24 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +     * This static method transforms the body of either the request or the response
Tu peux enlever `This static method ` pour juste commencer par : `Transforms the JSON body of either the request or the response`

2023-07-06 09:27 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/LogEntryTransformer.java
> +    static LogEntryTransformer hideJsonFields(List<String> jsonFieldKeysToHide, String replacement) {
Idéalement, il faudrait peut être donner un exemple : 
`hideJsonFields(List.of("password"), "***") will replace the JSON body `{"login": "john", "password": "azerty"}` by `{"login": "john", "password": "***"}`

2023-07-06 09:32 UTC, amanteaux requested changes

2023-07-06 09:32 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/RegexBuilder.java
> +public class RegexBuilder {
La classe pourrait être en visibilité `package`

2023-07-06 09:32 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/RegexBuilder.java
> +    static String computeUrlRegexList(List<String> urlRegexList) {
`static String computeUrlRegexList(List<String> urlRegexList) {` => `static String buildFilterUrlsRegex(List<String> urlsRegex) {`

2023-07-06 09:32 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/RegexBuilder.java
> +    static String regexHidingFields(List<String> keysToHide) {
`regexHidingFields` -> `buildHidingFieldsRegex`

2023-07-06 09:32 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/RequestPredicate.java
> +    default RequestPredicate filterUrlRegex(List<String> urlRegexList) {
`urlRegexList` => `urlsRegex`

2023-07-06 09:32 UTC, amanteaux commented on plume-admin-api-log/src/main/java/com/coreoz/plume/admin/RequestPredicate.java
> +     * @param urlRegexList : the URL regex list to be filtered
Idéalement il faudrait donner un mini exemple

2023-07-06 12:37 UTC, merged